config/routes.rb
Kwisatz::Application.routes.draw do

  resources :users
  resources :rounds do
    member do
      get :make_questions
    end
  end
  resources :questions do
    member do
      get :reveal
    end
  end
  
  resources :roundquestions
  
  
  
  resources :sessions,   :only => [:new, :create, :destroy]

  
  match '/signup', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  

end

app/models/question.rb
# == Schema Information
# Schema version: 20110713172022
#
# Table name: questions
#
#  id          :integer         not null, primary key
#  text        :string(255)
#  answer      :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  difficulty  :integer
#  category_id :integer
#

class Question < ActiveRecord::Base
  has_many :roundquestions
  belongs_to :category
  has_many :rounds, :through => :roundquestions
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def show
    @question=Question.find(params[:id])
    render :layout => false
  end
  
  def reveal
    @question=Question.find(params[:id])
    render :layout => false
  end
  
  def new
    @question=Question.new
    
  end

  def create
   @question = Question.new(params[:question])
    if @question.save
      render :nothing => true
    else
      render 'home'
    end
  end
    
  

  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_new.haml
= form_for(@round.questions[qid]) do |f|
  = f.label "Question: #{qid+1}"
  = f.text_field :text
  %br
  = f.label "Answer: "
  = f.text_field :answer

app/views/questions/_question.haml
!!! Strict
%html
	%head
		%meta{'http-equiv' => 'Content-Type', :content => "text/html; charset=iso-8859-1"}
		%title Untitled Document
	%body
		

app/views/questions/reveal.haml
%div.question
  = @question.answer
  %ul
    %li{:onclick=> "ShowQuestionBoard()"}
      Back to Board

app/views/questions/show.haml
%div.question
  = @question.text
  %ul
    %li{:onclick=> "ShowQuestionBoard()"}
      Back to Board
    %li{:onclick=> "ShowAnswer('#{reveal_question_path}','#{@question.id}')"}
      Show answer