config/routes.rb
Kwisatz::Application.routes.draw do

  resources :users
  resources :rounds do
    member do
      get :make_questions
    end
  end
  resources :questions do
    member do
      get :reveal
    end
  end
  
  resources :roundquestions
  
  
  
  resources :sessions,   :only => [:new, :create, :destroy]

  
  match '/signup', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  

end

app/models/round.rb
# == Schema Information
# Schema version: 20110712183301
#
# Table name: rounds
#
#  id                     :integer         not null, primary key
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  category_count         :integer
#  questions_per_category :integer
#

class Round < ActiveRecord::Base


  has_many :roundquestions
  has_many :categoryrounds
  has_many :questions, :through => :roundquestions
  has_many :categories, :through => :categoryrounds


  
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
   
  def show
    @title = "Round #{params[:id]}"
    @round = Round.find(params[:id])
    @questions = @round.questions
    @genres=["History", "Geography", "Cinema", "Science", "Literature", "Music"]
  end
  
  def add_category
    
    
  end

  def index
    @rounds = Round.paginate(:page => params[:page])
    @title = "All rounds"
  end
  
  def new
    @round=Round.new
    @title = "Create new round"
  end
  
  def add_questions
    question_count=@round.questions_per_category*@round.category_count
    question_count.times {@round.questions.new}
    render 'edit'
  end
  
  def edit
    @round=Round.find(params[:id])
  end
  
  def update
    @round=Round.find(params[:id])
    if @round.update_attributes(params[:round])
      redirect_to @round, :flash => { :success => "Round updated." } 
    end
  end
  
  def make_questions

  end

  def create
   @round = Round.new(params[:round])
    if @round.save
      render 'make_questions', :layout => false
    else
      @title = "Sign up"
      render 'new'
    end
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
  

  
end

app/views/rounds/OLDshow.haml
!!! Strict

%table{:id => "id-quiz-round-1"}
  %tr
    - @genres.each do |genre|
      %td
        = genre
  - q=0
  - 5.times do |i|
    %tr
      - 6.times do
        - q+=1
        %td
          %span
            = link_to "$#{(i+1)*100}", question_path(@round.questions.find_by_id(q))
    

app/views/rounds/_fields.haml
= render 'shared/error_messages', :object => f.object
.field
  = f.label "round name"
  = f.text_field :name
  %br
  = f.label "number of categories"
  = f.text_field :category_count
  %br
  = f.label "questions per category"
  = f.text_field :questions_per_category

app/views/rounds/_round.haml
%li
  = link_to round.name, round
-# <% if current_user.admin?%>
  = link_to "delete", round, :method => :delete, :confirm => "You sure?", :title => "Delete #{round.name}"

app/views/rounds/edit.haml
%h1 Edit Round
= form_for(@round) do |f|
  = render 'shared/error_messages', :object => f.object
  %table.jeopardy{:id => "id-quiz-round"}
    %tr.categories
      - @round.category_count.times do |category_id|
        %td
          = render 'categories', :category_id => category_id
  .actions
    = f.submit "Create round"

app/views/rounds/index.haml
%h1 Choose a Game
= will_paginate
%ul
  = render @rounds
= will_paginate

app/views/rounds/make_questions.haml
%table.jeopardy{:id => "make_quiz"}
  %tr.categories
    - @round.category_count.times do |i|
      %td
        .field
          %label Category
          %input{:id => "category#{i}"}
  - @round.questions_per_category.times do |difficulty|
    %tr
      - @round.category_count.times do |cat|
        %td{:id => "question#{cat}-#{difficulty}", 
            :onclick => "EditQuestion('#{cat}','#{difficulty}')"}
          &nbsp;
#question-form.cant-be-seen
  .field 
    %label Question
    %input{:id => "id-question-text"}
  .field
    %label Answer
    %input{:id => "id-question-answer"}
  %input{:type => :button, :onclick => "SaveQuestion(this,'#{@round.id}')"}

app/views/rounds/new.haml
%h1 New Round
= form_for(@round) do |f|
  = render 'shared/error_messages', :object => f.object
  = render 'fields', :f => f
  .actions
    %span{:onclick => "CreateRound()"}
      Create Round
#reply

app/views/rounds/show.haml
!!! Strict
%h1
%table.jeopardy{:id => "id-quiz-round-1"}
  %tr.categories
    - @round.categories.each do |category|
      %td
        = category.name
  - @round.questions_per_category.times do |diff|
    %tr
      - @round.category_count.times do |categ|        
        - question=@round.questions.select{|q| q.category.name==@round.categories[categ].name && q.difficulty==diff}[0]
        - question_path = question_path(question)
        - question_id = question.id
        %div
          %td{:id => "questionbox-#{question_id}", :onclick => "ShowQuestion('#{question_path}')"}
            %span
              %span{:id => "id-question-#{question_id}"}
                = "$#{(diff+1)*100}"
#reply