config/routes.rb
Kwisatz::Application.routes.draw do

  resources :users
  resources :rounds do
    member do
      get :make_questions
    end
  end
  resources :questions do
    member do
      get :reveal
    end
  end
  
  resources :roundquestions
  
  
  
  resources :sessions,   :only => [:new, :create, :destroy]

  
  match '/signup', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => 'pages#home'
  

end

app/views/layouts/_footer.html.haml
!!! Strict
%footer
  %br
  .menu.bottom-menu
    %ul
      %li
        = link_to "About", about_path
      %li.r
        = link_to "Contact", contact_path

app/views/layouts/_header.html.haml
!!! Strict
%header
  = link_to logo, root_path 
  .menu.top-menu
    %ul
      %li
        = link_to "Help", help_path
      %li
        = link_to "Sign out", signout_path
      %li
        = link_to "Sign in", signin_path
      %li.r
        = link_to "Rounds", rounds_path

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'custom2', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kwisatz</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! Strict
%html
  %head
    %title= @title
    = render 'layouts/stylesheets'
    = javascript_include_tag :defaults
    -# javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"
    = javascript_include_tag 'rails'
    = javascript_include_tag 'jquery.blockUI'
    = csrf_meta_tag
  %body
    .container
      = render 'layouts/header'
      %section(class='round')
        - flash.each do |key, value|
          %div(class="flash #{key}")
            = value
        = yield
      = render 'layouts/footer'